
[window]

# opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
# decorations_theme_variant = "Light" # "Dark"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"

size = 15.0

[general]
# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06


import = ["~/.dotfiles/alacritty/kanagawa.toml",]
