[window]
# padding.x = 10
# padding.y = 10

decorations = "none"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 15.0

[general]
import = ["~/.config/alacritty_themes/kanagawa_wave.toml"]

[env]
TERM = "xterm-256color"
